<template>
  <div class="home">
      <img class="home__brasil fade-in-final" src="../assets/mapa-brasil.png" />
      <transition-group name="slide-in" tag="section" v-for="(items, index) in mapa" :key="items" :class="[items.quadrante, items.pintado, 'animation-delay' + index]">  
      <!-- <section v-for="items in mapa" :key="items" :class="[items.quadrante, items.pintado]"></section> -->
      </transition-group>
  </div>
</template>

<script>
// @ is an alias to /src

export default {
  name: "Home",
  data () {
    return {
      mapa: [
        { quadrante: "f1", pintado: "dot-fill" },
        { quadrante: "c2", pintado: "dot-outline" },
        { quadrante: "d2", pintado: "dot-outline" },
        { quadrante: "e2", pintado: "dot-fill" },
        { quadrante: "f2", pintado: "dot-fill" },
        { quadrante: "h2", pintado: "dot-outline" },
        { quadrante: "i2", pintado: "dot-outline" },
        { quadrante: "j2", pintado: "dot-fill" },
        { quadrante: "b3", pintado: "dot-outline" },
        { quadrante: "c3", pintado: "dot-outline" },
        { quadrante: "d3", pintado: "dot-outline" },
        { quadrante: "e3", pintado: "dot-outline" },
        { quadrante: "f3", pintado: "dot-outline" },
        { quadrante: "g3", pintado: "dot-outline" },
        { quadrante: "h3", pintado: "dot-outline" },
        { quadrante: "i3", pintado: "dot-outline" },
        { quadrante: "j3", pintado: "dot-outline" },
        { quadrante: "k3", pintado: "dot-fill" },
        { quadrante: "b4", pintado: "dot-outline" },
        { quadrante: "c4", pintado: "dot-outline" },
        { quadrante: "d4", pintado: "dot-outline" },
        { quadrante: "e4", pintado: "dot-outline" },
        { quadrante: "f4", pintado: "dot-outline" },
        { quadrante: "g4", pintado: "dot-outline" },
        { quadrante: "h4", pintado: "dot-fill" },
        { quadrante: "i4", pintado: "dot-fill" },
        { quadrante: "j4", pintado: "dot-outline" },
        { quadrante: "k4", pintado: "dot-fill" },
        { quadrante: "l4", pintado: "dot-outline" },
        { quadrante: "m4", pintado: "dot-fill" },
        { quadrante: "a5", pintado: "dot-fill" },
        { quadrante: "b5", pintado: "dot-outline" },
        { quadrante: "c5", pintado: "dot-fill" },
        { quadrante: "d5", pintado: "dot-outline" },
        { quadrante: "e5", pintado: "dot-outline" },
        { quadrante: "f5", pintado: "dot-fill" },
        { quadrante: "g5", pintado: "dot-fill" },
        { quadrante: "h5", pintado: "dot-fill" },
        { quadrante: "i5", pintado: "dot-outline" },
        { quadrante: "j5", pintado: "dot-outline" },
        { quadrante: "k5", pintado: "dot-fill" },
        { quadrante: "l5", pintado: "dot-fill" },
        { quadrante: "m5", pintado: "dot-fill" },
        { quadrante: "n5", pintado: "dot-fill" },
        { quadrante: "o5", pintado: "dot-fill" },
        { quadrante: "a6", pintado: "dot-fill" },
        { quadrante: "b6", pintado: "dot-fill" },
        { quadrante: "c6", pintado: "dot-outline" },
        { quadrante: "d6", pintado: "dot-fill" },
        { quadrante: "e6", pintado: "dot-fill" },
        { quadrante: "f6", pintado: "dot-outline" },
        { quadrante: "g6", pintado: "dot-outline" },
        { quadrante: "h6", pintado: "dot-fill" },
        { quadrante: "i6", pintado: "dot-outline" },
        { quadrante: "j6", pintado: "dot-outline" },
        { quadrante: "k6", pintado: "dot-fill" },
        { quadrante: "l6", pintado: "dot-fill" },
        { quadrante: "m6", pintado: "dot-fill" },
        { quadrante: "n6", pintado: "dot-fill" },
        { quadrante: "o6", pintado: "dot-outline" },
        { quadrante: "a7", pintado: "dot-outline" },
        { quadrante: "b7", pintado: "dot-outline" },
        { quadrante: "c7", pintado: "dot-outline" },
        { quadrante: "d7", pintado: "dot-outline" },
        { quadrante: "e7", pintado: "dot-fill" },
        { quadrante: "f7", pintado: "dot-outline" },
        { quadrante: "g7", pintado: "dot-fill" },
        { quadrante: "h7", pintado: "dot-fill" },
        { quadrante: "i7", pintado: "dot-fill" },
        { quadrante: "j7", pintado: "dot-fill" },
        { quadrante: "k7", pintado: "dot-fill" },
        { quadrante: "l7", pintado: "dot-fill" },
        { quadrante: "m7", pintado: "dot-fill" },
        { quadrante: "n7", pintado: "dot-fill" },
        { quadrante: "o7", pintado: "dot-fill" },
        { quadrante: "b8", pintado: "dot-outline" },
        { quadrante: "c8", pintado: "dot-outline" },
        { quadrante: "d8", pintado: "dot-outline" },
        { quadrante: "e8", pintado: "dot-outline" },
        { quadrante: "f8", pintado: "dot-outline" },
        { quadrante: "g8", pintado: "dot-fill" },
        { quadrante: "h8", pintado: "dot-outline" },
        { quadrante: "i8", pintado: "dot-outline" },
        { quadrante: "j8", pintado: "dot-outline" },
        { quadrante: "k8", pintado: "dot-fill" },
        { quadrante: "l8", pintado: "dot-outline" },
        { quadrante: "m8", pintado: "dot-outline" },
        { quadrante: "n8", pintado: "dot-fill" },
        { quadrante: "f9", pintado: "dot-outline" },
        { quadrante: "g9", pintado: "dot-fill" },
        { quadrante: "h9", pintado: "dot-outline" },
        { quadrante: "i9", pintado: "dot-fill" },
        { quadrante: "j9", pintado: "dot-outline" },
        { quadrante: "k9", pintado: "dot-fill" },
        { quadrante: "l9", pintado: "dot-outline" },
        { quadrante: "m9", pintado: "dot-outline" },
        { quadrante: "n9", pintado: "dot-fill" },
        { quadrante: "g10", pintado: "dot-outline" },
        { quadrante: "h10", pintado: "dot-fill" },
        { quadrante: "i10", pintado: "dot-outline" },
        { quadrante: "j10", pintado: "dot-fill" },
        { quadrante: "k10", pintado: "dot-outline" },
        { quadrante: "l10", pintado: "dot-fill" },
        { quadrante: "m10", pintado: "dot-fill" },
        { quadrante: "n10", pintado: "dot-outline" },
        { quadrante: "g11", pintado: "dot-fill" },
        { quadrante: "h11", pintado: "dot-outline" },
        { quadrante: "i11", pintado: "dot-fill" },
        { quadrante: "j11", pintado: "dot-outline" },
        { quadrante: "k11", pintado: "dot-fill" },
        { quadrante: "l11", pintado: "dot-fill" },
        { quadrante: "m11", pintado: "dot-outline" },
        { quadrante: "g12", pintado: "dot-fill" },
        { quadrante: "h12", pintado: "dot-outline" },
        { quadrante: "i12", pintado: "dot-fill" },
        { quadrante: "j12", pintado: "dot-outline" },
        { quadrante: "k12", pintado: "dot-fill" },
        { quadrante: "l12", pintado: "dot-fill" },
        { quadrante: "h13", pintado: "dot-outline" },
        { quadrante: "i13", pintado: "dot-fill" },
        { quadrante: "j13", pintado: "dot-outline" },
        { quadrante: "k13", pintado: "dot-fill" },
        { quadrante: "h14", pintado: "dot-outline" },
        { quadrante: "i14", pintado: "dot-fill" },
        { quadrante: "j14", pintado: "dot-outline" },
        { quadrante: "h15", pintado: "dot-outline" },
        { quadrante: "i15", pintado: "dot-fill" },
        { quadrante: "j15", pintado: "dot-outline" },

      ],
    };
  },
  components: {
  }
};
</script>
